#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

import os, re
Import('env')

Import('mu2e_helper')

helper=mu2e_helper(env)

rootlibs  = env['ROOTLIBS']

mainlib = helper.make_mainlib ( [
    'art_Framework_Services_Registry',
    'art_Framework_Principal',
    'art_Utilities',
    'canvas',
    'cetlib',
    'cetlib_except',
    'mu2e_RecoDataProducts',
    rootlibs,

    'KinKal_Fit',
    'KinKal_Trajectory',
    'KinKal_Geometry',
    'KinKal_Detector',
    'KinKal_MatEnv',
    'KinKal_General',
    'mu2e_CalorimeterGeom',
    'mu2e_GeneralUtilities',
    'mu2e_GeometryService',
    'mu2e_GlobalConstantsService',
    'mu2e_DbTables',
    'mu2e_KinKalGeom',
    'mu2e_Mu2eKinKal',
    'mu2e_TrackerConditions',
    'mu2e_TrackerGeom',
] )

helper.make_plugins( [
    mainlib,
    'art_Framework_Core',
    'art_Framework_Principal',
    'art_Framework_Services_Registry',
    'art_Persistency_Provenance',
    'art_Utilities',
    'art_root_io_TFileService',
    'art_root_io_tfile_support',
    'canvas',
    'cetlib',
    'cetlib_except',
    'fhiclcpp',
    'fhiclcpp_types',
    'mu2e_DataProducts',
    'mu2e_RecoDataProducts',
    rootlibs,
    'trkana',

    'KinKal_Fit',
    'KinKal_Trajectory',
    'KinKal_Geometry',
    'KinKal_Detector',
    'KinKal_MatEnv',
    'KinKal_General',
    'mu2e_CalorimeterGeom',
    'mu2e_GeneralUtilities',
    'mu2e_GeometryService',
    'mu2e_GlobalConstantsService',
    'mu2e_DbTables',
    'mu2e_KinKalGeom',
    'mu2e_Mu2eKinKal',
    'mu2e_TrackerConditions',
    'mu2e_TrackerGeom',
] )

helper.make_dict_and_map( [
    mainlib,
    'Core',
    'art_Utilities',
    'canvas',
    'cetlib',
    'cetlib_except',
    'canvas'
] )
